name: Trigger Connect syncs to keep "hot and fresh"
on:
  schedule:
    # Every weekday (M-F) at every hour
    - cron: "0 * * * 1-5"
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d {} https://webhook.gatsbyjs.com/hooks/data_layer/data_source/publish/2f7d04ca-9a26-4b46-8609-2b65f76fca05
